spring:
  profiles:
    include:
      - db

  liquibase:
    enabled: false

  data:
    redis:
      port: 6379
      host: localhost

  application:
    name: message-ms

  devtools:
    remote:
      restart:
        enabled: true

  config:
    import: configserver:http://localhost:8888

  mail:
    host: smtp.gmail.com
    port: 587
    username: harunov21@gmail.com
    password: rvfx emss yjru zkof
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



server:
  port: 0