spring:
  profiles:
    include:
      - db

  liquibase:
    enabled: false

  data:
    redis:
      port: 6379
      host: localhost

  application:
    name: Comment-ms

  devtools:
    remote:
      restart:
        enabled: true

  config:
    import: configserver:http://localhost:8888


server:
  port: 0
