spring:
  profiles:
    include:
      - db

  liquibase:
    enabled: false

  data:
    redis:
      port: 6379
      host: localhost

  application:
    name: post-ms

  devtools:
    remote:
      restart:
        enabled: true

  config:
    import: configserver:http://localhost:8888



server:
  port: 0

#user-ms:
#  url: http://localhost:8081