spring:
  profiles:
    include:
      - db

  liquibase:
    enabled: false

  data:
    redis:
      port: 6379
      host: localhost

  application:
    name: post-ms

  devtools:
    remote:
      restart:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0

#user-ms:
#  url: http://localhost:8081